### ISSUE TITLE
Is dit nog in ontwikkeling?

### ISSUE THREAD

**Issue by Thijxx** [Rijkswaterstaat/wm-ws-dl#1]
Werkt iemand hier nog aan?

**Comment by walderveen** [comment]
De github wordt momenteel niet actief onderhouden. De webservices wel.

**Comment by tcdewit** [comment]
Komt er ook nieuwere documentatie beschikbaar? De laatste versie die ik kon vinden is een versie uit 2016:
https://www.rijkswaterstaat.nl/rws/opendata/DistributielaagWebservices-SUM-2v7.pdf
Ik merk verder dat ik mbt technische vragen over de webservices niet terecht kan bij de rws helpdesk (m'n vragen worden niet beantwoord en de helpdesk is telefonisch niet bereikbaar). Enig idee waar wel?

**Comment by walderveen** [comment]
Misschien dat dit een oplossing biedt [https://rijkswaterstaat.github.io/wm-ws-dl/#introduction](url)

**Comment by walderveen** [comment]
Blijkbaar werkt de link niet op die manier, Op de intro pagina https://github.com/Rijkswaterstaat/wm-ws-dl staat een link naar de nieuwere Slate documentatie.

**Comment by tcdewit** [comment]
Dank, die had ik inderdaad ook al gevonden. Ik loop bijv tegen issues aan bij het interpreteren van de datumtijd velden, waarover ik nergens antwoorden kan vinden.
Als ik in de request zoek naar begin/eind datumtijd 2021-06-09T12:00:00.000+01:00 (ISO8601) dan lijkt deze als 12:00 UTC te worden geinterpreteerd door de webservice. Ik krijg dan namelijk het resultaat terug voor 2021-06-09T13:00:00.000+01:00, wat op de rws website overeenkomt met 2021-06-09T14:00:00.000+02:00 (dus 14:00 CEST). Het verwarrende is wat mij betreft vooral dat de notatie met +01:00 suggereert dat er juist wordt gevraagd om een tijdstip in de UTC+1 tijdzone, maar ik dit tijdstip eigenlijk met T+0:00 moet lezen, wat voor de response dan weer niet geldt.

Verder is het erg onhandig dat als je resultaten opvraagt dmv "OphalenWaarnemingen" en er voor een klein deel van de gevraagde datumtijd-range geen resultaten zijn, je helemaal geen resultaten terugkrijgt. Het is dan (voor zover ik weet) een kwestie van trial en error om te achterhalen welke gegevens wel aanwezig zijn.

Andere issue is dat ik bij het opvragen van meetwaarden met regelmaat de waarde 9.99999999E8 terugkrijg (bijv bij het opvragen van voorspeld getij, WATHTEVERWACHT) voor de 2-4 oudste meetwaarden.

**Comment by TheoMul** [comment]
@walderveen ik loop tegen hetzelfde issue met tijdzones aan zoals @tcdewit beschrijft. Lijkt een probleem met zomertijd te zijn, als ik data opvraag uit februari zie ik dit verschijnsel niet. Issue is al langer aanwezig, bij een onderzoekje een jaar geleden ook al tegenaan gelopen.

**Comment by veenstrajelmer** [comment]
@TheoMul, @tcdewit mochten jullie geinteresseerd zijn in het subsetten van stations/parameter combinaties en het ophalen van data van de ddl in Python, kijk dan ook eens naar [ddlpy](https://github.com/Deltares/ddlpy). In dit pakket wordt de beschikbare data in de gewenste range opgehaald en gecombineerd. Ook zijn er sinds gisteren functies aanwezig die aantakken op de `OphalenWaarnemingen`, `OphalenLaatsteWaarnemingen`, `OphalenAantalWaarnemingen` en `CheckWaarnemingenAanwezig` van de ddl. Wellicht helpt dit.

Ik zal binnenkort zelf ook eens kijken naar de tijdzones of de de data die terugkomt continu is in de tijd bij het overschrijden van een zomer/wintertijd grens. Als ik het goed begrijp is de data en tijd in principe goed, maar is er een inconsistentie met ingevoerde en teruggekregen tijdzone, correct? Het zo mooi zijn als het in de ddl opgelost kan worden, maar anders zou dit in ddlpy afgevangen kunnen worden denk ik.

@tcdewit je geeft ook aan dat je 9.99999999E8 terugkrijgt, heb je wel op de kwaliteitscode gefilterd? ddlpy filtert automatisch de kwaliteteitswaardecode=99 uit de metingen, dus ik verwacht dat je dan een prettiger tijdreeks krijgt.

**Comment by tcdewit** [comment]
Interessant! Onder het motto "if it works don't fix it" denk ik dat ik voorlopig nog niet met ddlpy aan de slag ga, maar goed initiatief en goed te weten. Ik filter nu niet op kwaliteitscode (dank voor de tip) maar op sterk afwijkende waarden (<-1000 of >1000) wat bij getijde metingen prima voldoet.
Zomertijd/wintertijd heb ik zelf ook al eens naar gekeken en dat gaat prima. Highcharts gaat hier ook prima mee om zodat ik netjes een vloeiende curve krijg en de onderliggende data netjes de juiste tijdoffset gebruikt (gaat van 01:50 GMT+1 naar 3:00 GMT+2).
De datum notatie inconsequentie zit inderdaad nog steeds in de ddl, maar daar heb ik destijds een goede workaround voor geimplementeerd. Zou goed zijn als dat ooit eens netjes in de ddl wordt geprogrammeerd maar ik betwijfel of dat gaat gebeuren, gezien dan juist weer een hoop applicaties kunnen omvallen die een dergelijke workaround hebben gebruikt.

**Comment by veenstrajelmer** [comment]
@tcdewit dank voor je terugkoppeling. Ik heb even een apart issue aangemaakt voor wat je beschrijft: https://github.com/Rijkswaterstaat/wm-ws-dl/issues/9
Is dit wat jou betreft een volledige beschrijving? Dan kun je misschien dit issue sluiten.

**Comment by tcdewit** [comment]
Ik heb niet de rechten om deze te sluiten (is niet mijn issue) maar goed idee.
Vwb je nieuwe issue: de output klopt niet met de code, verder prima voorbeeld.

**Comment by veenstrajelmer** [comment]
Dank voor de oplettendheid, ik heb het issue aangepast, was een copy-paste foutje. @Thijxx kan het issue wat jou betreft ook gesloten worden? Jij bent waarschijnlijk de enige niet-moderator die dat kan.

**Comment by Thijxx** [comment]
> Dank voor de oplettendheid, ik heb het issue aangepast, was een copy-paste foutje. @Thijxx kan het issue wat jou betreft ook gesloten worden? Jij bent waarschijnlijk de enige niet-moderator die dat kan.

ja wat mij betreft prima, het is al even geleden allemaal :)
