### ISSUE TITLE
update WFS link in documentation

### ISSUE THREAD

**Issue by veenstrajelmer** [Rijkswaterstaat/wm-ws-dl#10]
The WFS link in the documentation on https://rijkswaterstaat.github.io/wm-ws-dl/?python#webfeatureservices is not available anymore. This also contained an incorrect CRS as documented in https://github.com/Rijkswaterstaat/wm-ws-dl/issues/6. There is a new WFS available via https://geo.rijkswaterstaat.nl/services/ogc/hws/wmdc15/ows?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities, as stated in https://github.com/Rijkswaterstaat/wm-ws-dl/issues/6#issuecomment-2033991662.

Could you please update the WFS links in the github.io documentation?

**Comment by TvLoon-RWS** [comment]
The maintenance of this page is discontinued. Please refer to www.rijkswaterstaatdata.nl/waterdata for documentation, examples, help and updates of our services.
