### ISSUE TITLE
allow distinction between historic and realtime stations

### ISSUE THREAD

**Issue by veenstrajelmer** [Rijkswaterstaat/wm-ws-dl#20]
It would be convenient to distinguish between hist and realtime stations. Maybe possible with BemonsteringsSoort.Code/Omschrijving=01/Rechtstreeksemeting versus BemonsteringsSoort.Code/Omschrijving=SB/Streekbemonstering. This is probably not the way to go, at least it is not straight forward.

Maybe always lowest/highest id?

This would also prevent duplicate station codes as described in https://github.com/Rijkswaterstaat/wm-ws-dl/issues/12

This would avoid confusion as described for OLST in https://github.com/openearth/ddlpy/issues/18#issuecomment-1986864407

**Comment by TvLoon-RWS** [comment]
duplicate with #12
