### ISSUE TITLE
WFS heeft verkeerd CRS?

### ISSUE THREAD

**Issue by LaurensJN** [Rijkswaterstaat/wm-ws-dl#6]
De WFS die aangegeven staat bij: https://rijkswaterstaat.github.io/wm-ws-dl/?python#webfeatureservices kan helaas niet worden geopend in QGIS. Er zijn twee CRS opties: RD New en WGS84.
![image](https://user-images.githubusercontent.com/23737460/148371879-c2559ece-05b2-43b7-96da-bb37d5bec62b.png)

Beiden geven een error 'Could not transform bounding box to target CRS'. Als ik alle features via de API download, staat er duidelijk aangegeven dat het coordinatenstelsel 25831 (ETRS89 / UTM 31N) is. Zou het zo kunnen zijn dat de CRS verkeerd staat aangegeven in de feature service? Alvast bedankt!

**Comment by walderveen** [comment]
Je kunt met het request de gewenste EPSG-code meegeven zodat er een RD New response wordt teruggegeven. Zie de GetCapabilities van de WFS. Zowel EPGS:28992 als 2857 worden ondersteund door de service.

https://waterwebservices.rijkswaterstaat.nl/services/distributielaagWFS/distributielaag_dbo?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities

**Comment by LaurensJN** [comment]
Bedankt voor de reactie. Ik kan de EPSG veranderen naar 25831, maar helaas krijg ik altijd de error 'Could not transform bounding box to target CRS' als ik de WFS laag toevoeg aan QGIS. Enig idee waar dat aan zou kunnen liggen?

**Comment by walderveen** [comment]
Misschien biedt dit een oplossing:
[https://github.com/qgis/QGIS/issues/34792](url)

**Comment by LaurensJN** [comment]
Ik heb een nieuwe versie van QGIS geinstalleerd en krijg helaas dezelfde foutmelding. Ook op mijn andere computer lukt het niet om de WFS te openen helaas. 

Op dit moment heb ik het anders opgelost: via de API alle features gedownload & geschreven naar een .csv bestand. Dat werkte prima.

**Comment by veenstrajelmer** [comment]
Op het moment kan de WFS in zijn geheel niet gevonden worden lijkt het:
![image](https://github.com/Rijkswaterstaat/wm-ws-dl/assets/60435591/f1b99243-c620-4e3f-86ca-6c2c46050f70)

**Comment by LaurensJN** [comment]
Kan je deze link proberen:
[https://geo.rijkswaterstaat.nl/services/ogc/hws/wmdc15/ows?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities](https://geo.rijkswaterstaat.nl/services/ogc/hws/wmdc15/ows?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities)

**Comment by LaurensJN** [comment]
Daarbij is er geen probleem meer met de CRS, daarom sluit ik de issue.

**Comment by veenstrajelmer** [comment]
Dank @LaurensJN, die link werkt inderdaad beter. Ik heb dit issue aangemaakt om de documentatie bij te werken: https://github.com/Rijkswaterstaat/wm-ws-dl/issues/10
