### ISSUE TITLE
API pull request python

### ISSUE THREAD

**Issue by emielshelf** [Rijkswaterstaat/wm-ws-dl#8]
Hi ik probeer via de RWS api data te downloaded mbhv Python maar krijg het niet voor elkaar. 
Hieronder mijn code.  Ik krijg de foutmelding:

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Iemand enig idee wat er fout is?

Als ik response.text aanroep krijg ik: Exception exceptionCode="InvalidParameterValue"

-------------------------------------

# LIBRARIES
import requests
import pandas as pd
import objectpath
import time
import datetime

# RWS SETTINGS
collect_observations = ('https://geo.rijkswaterstaat.nl/services/ogc/hws/wm/ows?VERSION=1.1.0/' +
                        'ONLINEWAARNEMINGENSERVICES_DBO/' +
                        'OphalenWaarnemingen')

# REQUEST VOOR OPHALEN WAARNEMINGEN
request = {
    "AquoPlusWaarnemingMetadata": {
    "AquoMetadata": [{"Compartiment": {"Code": "OW"},
                           "Eenheid": {"Code": "cm"},
                           "Grootheid": {"Code": "Hm0"}}],
    "Locatie": [{"X": 518882.333320247, "Y": 5760829.11729589, "Code": "EURPFM"}],
    "Periode": {"Begindatumtijd": "2012-01-27T09:00:00.000+01:00", "Einddatumtijd": "2012-01-27T09:01:00.000+01:00"}}
}

# GET DATA
response = requests.get(collect_observations, json=request)
result = response.json()

**Comment by ThiesVanLoon** [comment]
Dag Emiel, 
De volgende body zou wel moeten werken;

{
    "Locatie": {
        "X": "518882.333320247",
        "Y": "5760829.11729589",
        "Code": "EURPFM"},
    "AquoPlusWaarnemingMetadata": {
        "AquoMetadata": {
            "Grootheid":{
                "Code": "Hm0"
            }
        }
    },
    "Periode": {
        "Begindatumtijd": "2012-01-27T09:00:00.000+01:00",
        "Einddatumtijd": "2012-01-27T09:01:00.000+01:00"
    }
    }

Misschien zou je de grootheid uit moeten schrijven van "cm" naar "centimeters"
Anders zouden ze je ook goed kunnen helpen bij de servicedesk van Rijkswaterstaat;
https://www.rijkswaterstaat.nl/formulieren/contactformulier-servicedesk-data

**Comment by emielshelf** [comment]
@ThiesVanLoon, bedankt, het werkt!
